# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 255d3f139097d007985937ee80bc01c4acec589d07154cd884f88e87b4b818745a518fa02d6fdc3cb9861f4fd8c3a7db1635fb70d42b750d089afb21df4e5045

test:
  secret_key_base: 9be424a4533bc41cd549d4ea9334aede1e7c3bdd239b59331ce8fdc3ce21ab91a273cf056ad093ec55979be0c1952dc67c1832cdd87c31c4a6ebcb07677da01a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
